USE [master]
GO

/****** Object:  Database [SalesOrder]    Script Date: 2024/09/17 11:11:03 ******/
CREATE DATABASE [SalesOrder]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SalesOrder', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\SalesOrder.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SalesOrder_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\SalesOrder_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SalesOrder].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SalesOrder] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SalesOrder] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SalesOrder] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SalesOrder] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SalesOrder] SET ARITHABORT OFF 
GO

ALTER DATABASE [SalesOrder] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SalesOrder] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SalesOrder] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SalesOrder] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SalesOrder] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SalesOrder] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SalesOrder] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SalesOrder] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SalesOrder] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SalesOrder] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SalesOrder] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SalesOrder] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SalesOrder] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SalesOrder] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SalesOrder] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SalesOrder] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SalesOrder] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SalesOrder] SET RECOVERY FULL 
GO

ALTER DATABASE [SalesOrder] SET  MULTI_USER 
GO

ALTER DATABASE [SalesOrder] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SalesOrder] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SalesOrder] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SalesOrder] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SalesOrder] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SalesOrder] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SalesOrder] SET QUERY_STORE = ON
GO

ALTER DATABASE [SalesOrder] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [SalesOrder] SET  READ_WRITE 
GO

